# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef0a927a445c3a3acdd5dfc6892a658fb5a640c1105cc76b8b2e577548cab3ca3a9d19a401854852fe842188a18ed84eb434b68486a03f83d9ffb2133b1f22ac

test:
  secret_key_base: 5006bb103410c5cc1b00d38d1f4d74bb039a69b4d61ed50d9129a0a6a3074dcb45b87f73b72a4d14369c752aabfc423ba6775ff2dc0b3cb8d333ffa953d3826a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  config.secret_key_base = ENV["SECRET_KEY_BASE"]
